apiVersion: v1
kind: Namespace
metadata:
  name:  mynamespace 

---

apiVersion: v1
kind: ResourceQuota
metadata:
  #computing quotas
  name:  user-compute-quota
  namespace:  mynamespace
spec:
  #makes sure the requirements are met, any pod with resource requests and limit will not run
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory:  2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  #object resource quoatas
  name:  user-object-quota
  namespace: mynamespace
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"