apiVersion: v1
kind: Pod
metadata:
  name: mypod-volumesecret
  labels:
    name: myapp
spec:
  containers:
  - name: volumesecret
    image: redis:latest
    volumeMounts:
      - name:  foo
        mountPath:  "/etc/foo"
        readOnly: true


    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    
  volumes:
  - name: foo
    secret:
      secretName: mysecret-manifest
      # this mounts mysecret-manifest.yaml secret at the location
      # /etc/foo of our Pod
