kind: Service
apiVersion: v1
metadata:
  name:  cassandra-service
  labels:
    app: cassandra
spec:
  #specifies it's a headless service
  clusterIP: None
  ports:
  - port:  9042
  selector:
    app: cassandra