apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          env:
            - name: "MYSQL_USER"
              value: "helloworld"
            - name: "MYSQL_PASSWORD"
              value: "password"
            - name: "MYSQL_DATABASE"
              value: "helloworld"
            - name: "MYSQL_ROOT_PASSWORD"
              value: "rootpassword"
              # valueFrom: 
              #  secretKeyRef: 
              #   name: mysecret
              #   key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data