#!/usr/local/bin/ansible-playbook
- name:  Shows the Use of Comparison Operators
  hosts: all
  remote_user: ec2-user
  become: yes
  gather_facts: true # disabling gathering facts
  become_user: root

  vars:
    a : "HELLO"
    x : "hello"
    b: 10
    c: 20
    # | for jinja method and . for accessing python methods on the variables.
  tasks:
  - name:  "Operation 1"
    debug:
      msg:
      - "Value of {{a}}, Value of b is {{b}}, Value of c is {{c}}"
      - "Is b greater than c : {{ b > c }}"
      - "Is b less than c : {{ b < c }}"
      - "Is b equal to  c : {{ b == c }}"
      - "Is b not equal to c : {{ b != c }}"
      - "Is b greater than or equal to c : {{ b >= c }}"
      - "Is b less than or equal to c : {{ b <= c }}"
      - "#####################################################"
      - "Value of {{a}}, {{x}}"
      - "Is a greater than x : {{ a > x }}"
      - "Is a less than x : {{ a < x }}"
      - "Is a equal to  x : {{ a == x }}"
      - "Is a not equal to x : {{ a != x }}"
      - "Is a greater than or equal to x : {{ a >= x }}"
      - "Is a less than or equal to x : {{ a <= x }}"