#!/usr/local/bin/ansible-playbook
- name:  ansible blocks and rescue
  hosts: all
  remote_user: ec2-user
  gather_facts: true # disabling gathering facts

  vars:
    anonymous_enable: yes
    local_enable: yes
    write_enable: yes
    anon_upload_enable: yes

  tasks:
  - block:
    - name: Install the FTP Vsftpd
      yum: 
        name: vsftpd
        state: present

    - name: take backup of existing config
      copy:
        src: /etc/vsftpd/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf.bkp
        remote_src: yes

    - name: use jinja2 template to configure vsftpd
      template:
        src: vsftpd.j2
        dest: /etc/vsftpd/vsftpd.conf
      #View Template Values
    - name : View Custom jinja2 template Values
      command: 'cat /etc/vsftpd/vsftpd.conf'
      register: jinja2_out
    - debug: var=jinja2_out
    # assumes this custom configuration fails from this block
    - name: This will fail
      command: "ls -l /tmp/does-not-exist"
    become: yes
    become_user: root
    # ignore_errors: yes
    
    rescue:
    - name: Rescue block (perform recovery)
      debug:
        msg: 'Something failed, restoring vstpd.conf  from backup'
    - name: Restoring Original file
      copy:
        src: /etc/vsftpd/vsftpd.conf.bkp
        dest: /etc/vsftpd/vsftpd.conf
        remote_src: yes # happens on the remote machine
    - name: View conf file
      command: 'cat /etc/vsftpd/vsftpd.conf'
      register: std_out
    - debug: var=std_out
  
    always:
    - name: Restarting vsftpd
      service:
        name: vsftpd
        state: restarted