#!/usr/local/bin/ansible-playbook
- name:  Shows the Use of Comparison Operators
  hosts: all
  remote_user: ec2-user
  become: yes
  gather_facts: true # disabling gathering facts
  become_user: root

  tasks:
  - name: Ensure Apache is at the Latest Version
    yum:
      name: httpd
      state: present
    notify:
    # calls the handler after the task is actually executed with changed of 1
    # unlike the previous that skipped the tasks
      - handlerOne
      - handlerTwo

  handlers:
  - name: handlerOne
    service:
      name: httpd
      state: restarted