#!/usr/local/bin/ansible-playbook
- name:  Including the Playbook
  hosts: all
  remote_user: ec2-user
  become: yes
  gather_facts: true # disabling gathering facts
  become_user: root

  tasks:
    - name: Play 2 - Task 1
      debug:
        msg: Play 2 - Task 1
    # - include: play2.yml include doesn't work for plays anymore