apiVersion: v1
kind: Namespace
metadata:
  name:  mynamespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  perter-access
  namespace:  mynamespace
rules: 
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["","extensions", "apps"]
  resources:  ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name:  peter-role-binding
  namespace:  mynamespace
subjects:
- kind: User
  name:  peter
  namespace:  mynamespace
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name:  perter-access
  apiGroup: rbac.authorization.k8s.io