apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-pod-reader
  namespace: mynamespace
subjects:
  - kind: ServiceAccount
    name: my-serviceaccount
    namespace: mynamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # the name of the Role you created beforeHand
  name: perter-access