apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-storage
spec:
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: aws-standard
  accessModes:
    - ReadWriteOnce
