#!/usr/local/bin/ansible-playbook
- name:  Introduction Ansible Playbooks
  hosts: all
  remote_user: ec2-user
  become: yes
  # gather_facts: false # disabling gathering facts
  become_user: root
  tasks:
  - name:  "Ensure Apache is at the Latest Version"
    yum:
      name:  httpd
      state: latest
  - name:  "Ensure Apache is running"
    service:
      name:  httpd
      state: started